stages:
- name: maven package
  steps:
  - runScriptConfig:
      image: 192.168.144.132/base/maven-aliyun:3.5.4-jdk-8-alpine
      shellScript: mvn clean package -Dmaven.test.skip=true
  when:
    event: {}
- name: docker build & publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: b2b/springboot-docker:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.144.132
    env:
      PLUGIN_DEBUG: true
      PLUGIN_INSECURE: 192.168.144.132
      PLUGIN_MIRROR: https://mrpxuz76.mirror.aliyuncs.com
    when:
      event: {}
- name: deploy workload
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    event: {}
timeout: 10
branch:
  include:
  - master
